### PR TITLE
feat: Encapsulate http.Client, API endpoint, and product in struct

### PR DESCRIPTION
**Pull request by kevinbowrin**
- Simplify tests
- Change 'Check' to 'Verify' to better align with underlying API
- Added VerifyWithContext method

### CODE REVIEW

**Comment by kevinbowrin** [comment]
This PR significantly changes the package API. Instead of calling the package-level Check() function, clients would instead create a GumroadProduct struct and run its Verify() method.

I renamed 'Check' to 'Verify' to line up better with the underlying API call at `licenses/verify`.

Making this change allows clients to more easily change the underlying API endpoint URL and the http.Client. (https://0x46.net/thoughts/2018/12/29/go-libraries/).

I also simplified the tests. Since we can easily change the http.Client now, we can use the one provided by httptest.NewTLSServer().Client(). For the MITM test, we can take advantage of the fact that the default client doesn't accept the TLS cert used by httptest.NewTLSServer(). That means we don't need the generate calls anymore.

**Review by caarlos0 — APPROVED** [review]
lgtm, thank you!

maybe @MrGossett can chime in as well

**Comment by kevinbowrin** [comment]
Forgot to delete generate_cert.go, latest push fixes that.

**Comment by MrGossett** [comment]
LGTM! I'm a fan of removing globals.

**Pull request merged**
